DROP TABLE IF EXISTS lists CASCADE;
DROP TABLE IF EXISTS tasks CASCADE;
DROP TABLE IF EXISTS statuses;
DROP TABLE IF EXISTS headings CASCADE;
DROP TABLE IF EXISTS tags CASCADE;
DROP TABLE IF EXISTS tasks_tags;
DROP TABLE IF EXISTS reminders CASCADE ;
DROP TABLE IF EXISTS reminder_settings;