DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS lists CASCADE;
DROP TABLE IF EXISTS tasks CASCADE;
DROP TABLE IF EXISTS statuses;
DROP TABLE IF EXISTS tags CASCADE;
DROP TABLE IF EXISTS reminders CASCADE ;
DROP TABLE IF EXISTS reminder_settings;