CREATE TABLE IF NOT EXISTS users
(
    id         character varying PRIMARY KEY,
    email      character varying NOT NULL,
    password   character varying NOT NULL,
    first_name character varying NOT NULL,
    last_name  character varying NOT NULL,
    phone      character varying,
    updated_at timestamp WITH TIME ZONE NOT NULL DEFAULT now(),
    deleted_at timestamp WITH TIME ZONE DEFAULT NULL
);

CREATE UNIQUE INDEX active_users_email_key ON users (email) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS statuses
(
    id          int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    status_name character varying NOT NULL
);

CREATE TABLE IF NOT EXISTS attachments
(
    id                character varying PRIMARY KEY ,
    file_name         character varying NOT NULL,
    file_url          character varying NOT NULL,
    attachment_size   character varying NULL,
    attached_by_id    character varying NOT NULL,
    updated_at        timestamp WITH TIME ZONE NOT NULL DEFAULT now(),
    deleted_at        timestamp WITH TIME ZONE DEFAULT NULL
);

CREATE INDEX IF NOT EXISTS idx_attached_by_id ON attachments(attached_by_id);

CREATE TABLE IF NOT EXISTS reminders
(
    id             character varying PRIMARY KEY,
    user_id        character varying NOT NULL,
    content        character varying NOT NULL,
    read           boolean NOT NULL,
    updated_at     timestamp WITH TIME ZONE NOT NULL DEFAULT now(),
    deleted_at     timestamp WITH TIME ZONE DEFAULT NULL
);

CREATE INDEX IF NOT EXISTS idx_user_id ON reminders(user_id);

CREATE TABLE IF NOT EXISTS reminder_settings
(
    id       int PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    interval character varying NOT NULL
);

ALTER TABLE attachments ADD FOREIGN KEY (attached_by_id) REFERENCES users (id);
ALTER TABLE reminders ADD FOREIGN KEY (user_id) REFERENCES users (id);
