DROP TABLE IF EXISTS lists CASCADE;
DROP TABLE IF EXISTS tasks CASCADE;
DROP TABLE IF EXISTS statuses CASCADE;
DROP TABLE IF EXISTS headings CASCADE;
DROP TABLE IF EXISTS tags CASCADE;
DROP TABLE IF EXISTS tasks_tags CASCADE;
DROP TABLE IF EXISTS reminders CASCADE ;
DROP TABLE IF EXISTS reminder_settings;